#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "米拉的自留地"
# Short bio or description (displayed in the header)
description: "坎坷之路，终抵群星 Per Aspera Ad Astra"

#
# 可选设置：Flags below are optional
#


#博客logo图片
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/Miralworth/Miralworth.github.io/raw/master/images/blog.jpg

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://github.com/Miralworth/Miralworth.github.io/raw/master/images/favicon.ico



# 菜单中的按钮
# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 首页 #Blog
    url: /
  - name: 关于
    url: /about
  - name: 归档 #Archive
    url: /archive
  - name: 标签
    url: /tags


# 每页的文章数
# Pagination
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->


# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
# Includes an icon in the footer for each username you enter
footer-links:
  weibo: miralworth #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<username>
  dribbble:
  zhihu: 
  email: 
  facebook:
  flickr:
  github: 
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  #twitter: frommidworld
  youtube:
  lofter: miralworth

# 站点页脚的文字
# Text under the icons in footer
footer-text: Copyright (c) 2020 Miralworth


# 评论，注意，请不要同时添加多种不同的评论区
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点
disqus: miralworth
# fromendworld

# Gitalk
gitalk:
  clientID: #9e4cfdab5f02498fe6a7
  clientSecret: #a0e0c6fa8510fc7929fdef95c1c0664f68debb43
  repo: #miralworth.github.io
  owner: #Miralworth

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://miralworth.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: 

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

